# Generated by Django 5.1.1 on 2024-10-16 09:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PercentCashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_percent', models.IntegerField(verbose_name='Процент за мобильное приложение')),
                ('web_percent', models.IntegerField(verbose_name='Процент за веб-сайт')),
                ('magazine_percent', models.IntegerField(verbose_name='Процент за магазин')),
            ],
            options={
                'verbose_name': 'Процент кэшбэка',
                'verbose_name_plural': 'Проценты кэшбэка',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reports/', verbose_name='Картинка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('contact_number', models.CharField(max_length=15, verbose_name='Контактный номер')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефонный номер')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('opening_hours', models.TimeField(blank=True, null=True, verbose_name='Время открытия')),
                ('closing_hours', models.TimeField(blank=True, null=True, verbose_name='Время закрытия')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('telegram_chat_ids', models.TextField(blank=True, help_text='Введите чат-айди через запятую', null=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Telegram Chat IDs')),
                ('self_pickup_available', models.BooleanField(default=True, verbose_name='Самовывоз доступен')),
            ],
            options={
                'verbose_name': 'Ресторан',
                'verbose_name_plural': 'Рестораны',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Самовывоз')], max_length=255)),
                ('infosystem', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('created', 'Создан'), ('paid', 'Оплачен'), ('delivered', 'Доставлен')], max_length=255)),
                ('pay_method', models.CharField(choices=[('cash', 'Наличные'), ('visa', 'Виза'), ('elcart', 'Эльекарт'), ('elsom', 'Элсом'), ('o_money', 'О деньги')], max_length=255)),
                ('change', models.FloatField()),
                ('total', models.FloatField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('addresses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.useraddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('amount', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
    ]
