# Generated by Django 5.1.1 on 2024-10-18 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_bonustransaction_options'),
        ('catalog', '0003_alter_product_activity_alter_product_category_and_more'),
        ('orders', '0002_alter_order_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Товар в заказ', 'verbose_name_plural': 'Товары в заказе'},
        ),
        migrations.AlterField(
            model_name='order',
            name='addresses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.useraddress', verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='change',
            field=models.FloatField(verbose_name='Сдача'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='infosystem',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инфосистема'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('visa', 'Виза'), ('elcart', 'Эльекарт'), ('elsom', 'Элсом'), ('o_money', 'О деньги')], max_length=255, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('paid', 'Оплачен'), ('delivered', 'Доставлен')], max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(verbose_name='Итого'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Самовывоз')], max_length=255, verbose_name='Способ получения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='amount',
            field=models.FloatField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order', verbose_name='Заказы'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.FloatField(verbose_name='Количество'),
        ),
    ]
