# Generated by Django 5.1.1 on 2024-11-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_options_alter_order_addresses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bonus_used',
            field=models.FloatField(default=0, verbose_name='Использованные бонусы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='change',
            field=models.FloatField(default=0, verbose_name='Сдача'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0, verbose_name='Итого'),
        ),
    ]
