# Generated by Django 5.0.7 on 2024-11-14 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_favorite_products'),
        ('orders', '0004_order_bonus_used_alter_order_change_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='bonus_used',
            new_name='bonus_spent',
        ),
        migrations.AddField(
            model_name='order',
            name='bonus_earned',
            field=models.FloatField(default=0, verbose_name='Заработанные бонусы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='addresses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.useraddress', verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('visa', 'Виза'), ('elcart', 'Эльекарт'), ('elsom', 'Элсом'), ('o_money', 'О деньги')], default='cash', max_length=255, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Самовывоз')], default='pickup', max_length=255, verbose_name='Способ получения'),
        ),
    ]
