version: "3.10"

services:

  app:
    image: niiazovm/steak-dream:latest
    volumes:
      - ./media:/app/media
    ports:
    - "8001:8001"
    command: bash -c "python manage.py collectstatic --no-input && python manage.py migrate && daphne config.asgi:application -b 0.0.0.0 -p 8001"
    env_file:
      - .env

