# Generated by Django 5.1.1 on 2024-09-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_favicon',
            field=models.FileField(blank=True, null=True, upload_to='site/favicon/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_logo_footer',
            field=models.FileField(blank=True, null=True, upload_to='site/logo_footer/'),
        ),
    ]
