# Generated by Django 5.1.1 on 2024-09-30 11:39

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('image', models.ImageField(blank=True, null=True, upload_to='advertisements/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Рекламные объявления',
            },
        ),
        migrations.CreateModel(
            name='BonusPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_app_image', models.FileField(blank=True, null=True, upload_to='bonus_pages', verbose_name='Мобильное приложение')),
                ('mobile_app_text', models.TextField(blank=True, null=True, verbose_name='Текст приложения')),
                ('mobile_app_color', colorfield.fields.ColorField(blank=True, default='#000000', image_field=None, max_length=25, null=True, samples=None, verbose_name='Цвет карточки приложения')),
                ('bonus_image', models.FileField(blank=True, null=True, upload_to='bonus_pages', verbose_name='Картинка карточки бонусов')),
                ('bonus_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок карточки бонусов')),
                ('bonus_text', models.TextField(blank=True, null=True, verbose_name='Текст карточки бонусов')),
                ('bonus_color', colorfield.fields.ColorField(blank=True, default='#000000', image_field=None, max_length=25, null=True, samples=None, verbose_name='Цвет карточки бонусов')),
                ('bottom_card_text', models.TextField(blank=True, null=True, verbose_name='Нижняя часть карточки')),
                ('bottom_cart_color', colorfield.fields.ColorField(blank=True, default='#000000', image_field=None, max_length=25, null=True, samples=None, verbose_name='Цвет нижней части карточки')),
            ],
            options={
                'verbose_name': 'Бонусная страница',
                'verbose_name_plural': 'Бонусная страница',
            },
        ),
    ]
