# Generated by Django 5.1.1 on 2024-10-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_desktop',
            field=models.ImageField(upload_to='images/banners/desktop/%Y/%m/', verbose_name='Картинка крупная'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_mobile',
            field=models.ImageField(upload_to='images/banners/mobile/%Y/%m/', verbose_name='Картинка мобильная'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.CharField(max_length=255, verbose_name='Имейл'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='icon',
            field=models.FileField(upload_to='payment_icons', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='link',
            field=models.CharField(max_length=100, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.FileField(upload_to='social_icons', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='link',
            field=models.CharField(max_length=100, verbose_name='Ссылка'),
        ),
    ]
