# Generated by Django 5.1.1 on 2024-11-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='similar_products',
            field=models.ManyToManyField(blank=True, related_name='similar_to', to='catalog.product', verbose_name='Похожие товары'),
        ),
        migrations.AlterField(
            model_name='product',
            name='activity',
            field=models.BooleanField(default=True, verbose_name='Активны��'),
        ),
    ]
