# Generated by Django 5.1.1 on 2024-11-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_similar_products_alter_product_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='activity',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
    ]
