# Generated by Django 5.1.1 on 2024-10-18 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_product_options_and_more'),
        ('yaros_connector', '0003_alter_supplier_infosystem_alter_supplier_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='activity',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/images/products', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='measure',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sort_priority',
            field=models.IntegerField(default=0, verbose_name='Приоритет сортировки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID поставщика'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier_integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yaros_connector.supplier', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
