# Generated by Django 5.1.1 on 2024-09-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_image_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sort_priority',
            field=models.IntegerField(default=0),
        ),
    ]
