# Generated by Django 5.0.7 on 2024-11-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_discount_product_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_total_amount',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Минимальная сумма заказа'),
        ),
    ]
