# Generated by Django 5.1.1 on 2024-09-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
