# Generated by Django 5.0.7 on 2024-11-14 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_is_new_product_is_popular'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала акции')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания акции')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание акции')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/promotions')),
                ('required_quantity', models.PositiveIntegerField(default=1, verbose_name='Количество для подарка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Акционный продукт',
                'verbose_name_plural': 'Акционные продукты',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='promotional_products',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.promotionalproduct', verbose_name='Акционные продукты'),
        ),
    ]
