# Generated by Django 5.1.1 on 2024-10-18 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonustransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Бонусная транзакция', 'verbose_name_plural': 'Бонусные транзакции'},
        ),
    ]
