# Generated by Django 5.1.1 on 2024-11-07 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_bonustransaction_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusSystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Бонус за регистрацию')),
                ('birthday_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Бонус за день рождения')),
                ('child_birthday_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Бонус за день рождения детей')),
                ('order_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Бонус за заказ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Настройки системы бонусов',
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ребенок',
                'verbose_name_plural': 'Дети',
            },
        ),
    ]
