# Generated by Django 5.0.7 on 2024-11-15 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_bonussystemsettings_child'),
        ('catalog', '0004_product_discount_product_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonussystemsettings',
            name='max_age',
            field=models.PositiveIntegerField(default=18, verbose_name='Максимальный возраст для ребенка'),
        ),
        migrations.AddField(
            model_name='bonussystemsettings',
            name='max_children',
            field=models.PositiveIntegerField(default=5, verbose_name='Максимальное количество детей'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_products',
            field=models.ManyToManyField(blank=True, to='catalog.product', verbose_name='Избранные товары'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский'), ('O', 'Другой')], max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='user',
            name='qr_code_data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Промокод')),
                ('is_personal', models.BooleanField(default=False, verbose_name='Именной')),
                ('usage_limit', models.PositiveIntegerField(default=1, verbose_name='Количество использований')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания действия')),
                ('coins_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Количество койнов')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promo_images/', verbose_name='Изображение для попапа')),
                ('users', models.ManyToManyField(blank=True, related_name='promo_codes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
        ),
        migrations.CreateModel(
            name='UserPromotionalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_quantity', models.PositiveIntegerField(default=0, verbose_name='Купленное количество')),
                ('promotional_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_counters', to='catalog.promotionalproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_promotions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'promotional_product')},
            },
        ),
    ]
