# Generated by Django 5.0.7 on 2024-11-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qr_code_data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
