
# Generated by Django 5.0.7 on 2024-11-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_qr_code_data'),
        ('catalog', '0006_product_is_new_product_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_products',
            field=models.ManyToManyField(blank=True, to='catalog.product', verbose_name='Избранные товары'),
        ),
    ]
