# Generated by Django 5.0.7 on 2024-11-14 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_gender'),
        ('catalog', '0007_promotionalproduct_product_promotional_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonussystemsettings',
            name='max_age',
            field=models.PositiveIntegerField(default=18, verbose_name='Максимальный возраст для ребенка'),
        ),
        migrations.AddField(
            model_name='bonussystemsettings',
            name='max_children',
            field=models.PositiveIntegerField(default=5, verbose_name='Максимальное количество детей'),
        ),
        migrations.AlterField(
            model_name='child',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserPromotionalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_quantity', models.PositiveIntegerField(default=0, verbose_name='Купленное количество')),
                ('promotional_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_counters', to='catalog.promotionalproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_promotions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'promotional_product')},
            },
        ),
    ]
