# Generated by Django 5.1.1 on 2024-10-18 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_admin_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='chatroom',
            options={'verbose_name': 'Чат-комната', 'verbose_name_plural': 'Чат-комнаты'},
        ),
    ]
