# Generated by Django 5.1.1 on 2024-10-18 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yaros_connector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
    ]
