# Generated by Django 5.1.1 on 2024-10-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaros_connector', '0002_alter_supplier_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='infosystem',
            field=models.CharField(max_length=255, verbose_name='Инфосистема'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='publication',
            field=models.CharField(max_length=255, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='url',
            field=models.CharField(max_length=255, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='username',
            field=models.CharField(max_length=255, verbose_name='Имя пользователя'),
        ),
    ]
